### ISSUE TITLE
`domain 0.10.3` is incompatible with `time 0.3.41`

### ISSUE THREAD

**Issue by pront** [NLnetLabs/domain#502]
Is this something that you plan to address in the next update? Thank you!

Ref: 
* PR: https://github.com/vectordotdev/vrl/pull/1358
* Failure: https://github.com/vectordotdev/vrl/actions/runs/14041640343/job/39312991105

**Comment by Philip-NLnetLabs** [comment]
Yes, that is fixed in main.

**Comment by PSeitz** [comment]
Can we have a release with the fix?

**Comment by PSeitz** [comment]
The issue still exists for me on main. I opened https://github.com/NLnetLabs/domain/pull/503 to fix the issue

**Comment by Philip-NLnetLabs** [comment]
Thanks. I tested main and it seemed to work. But I must have done something wrong.

**Comment by pront** [comment]
Thanks @PSeitz!
@Philip-NLnetLabs when do you plan to release a new version?

**Comment by Philip-NLnetLabs** [comment]
We don't have solid plans yet. But we have a large PR that should land soon. So it makes sense to make a release shortly after that.

**Comment by PSeitz** [comment]
@Philip-NLnetLabs  I think that should be a `patch` release, since with a version bump it may require quite some time until every dependency upgraded
